feat: add create command for sesh

diff --git a/scripts/tmux-sessionizer b/scripts/tmux-sessionizer
--- a/scripts/tmux-sessionizer
+++ b/scripts/tmux-sessionizer
@@ -4,6 +4,7 @@ usage() {
     echo "Usage: tmux-sessionizer [--help | -h] [--open | -o <directory>] [directory...]"
     echo "  --help, -h: Show this help message"
     echo "  --open, -o: Open a directory in a new tmux session"
+    echo "  --create, -c: Create a new project in your projects folder"
     echo "  directory:  Search in the provided directories for a session to open"
     echo "  If no directory is provided, the script will search for directories in ~/personal and ~/work"
 }
@@ -11,6 +12,12 @@ usage() {
 if [[ $# -eq 1 && ($1 == "--help" || $1 == "-h") ]]; then
     usage
     exit 0
+fi
+
+if [[ $# -eq 1 && ($1 == "--create" || $1 == "-c") ]]; then
+    echo "Error: --create requires a directory" >&2
+    usage
+    exit 1
 fi
 
 if [[ $# -eq 1 && ($1 == "--open" || $1 == "-o") ]]; then
@@ -25,6 +32,9 @@ if [[ $# -eq 0 ]]; then
     selected=$(find ~/personal ~/work -mindepth 1 -maxdepth 1 -type d | fzf)
 elif [[ $# -eq 2 && $1 == "--open" || $1 == "-o" ]]; then
     selected=$2
+elif [[ $# -eq 2 && $1 == "--create" || $1 == "-o" ]]; then
+    selected=$2
+    mkdir -p $selected
 else
     selected=$(find "$@" -mindepth 1 -maxdepth 1 -type d | fzf)
 fi
